osx_image: xcode8.1
language: objective-c
script:
- brew install node
- npm install --global hasha-cli
- xcodebuild clean build -arch arm64 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
- mkdir Payload
- cp -R build/Release-iphoneos/Dark_Recipe.app Payload
- zip -r Jailbreak-$(echo $TRAVIS_COMMIT).ipa Payload/
- ls
- cat Jailbreak-$(echo $TRAVIS_COMMIT).ipa | hasha -a md5
- cat Jailbreak-$(echo $TRAVIS_COMMIT).ipa | hasha -a md5 > Jailbreak-$(echo $TRAVIS_COMMIT).ipa.md5
- export RELEASE_MD5="Jailbreak-$(echo $TRAVIS_COMMIT).ipa.md5"
- export RELEASE_IPA="Jailbreak-$(echo $TRAVIS_COMMIT).ipa"
after_success:
- npm install request-promise
- npm install request
- npm install jsonwebtoken
- node release.js
